import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
    return (
        <Html lang="en">
            <Head>
                <link rel="icon" href="/rick-morty.png" />
                <meta
                    name="Rick an Morty"
                    content="Generated by create next app"
                />
                <link
                    id="app-theme"
                    rel="stylesheet"
                    type="text/css"
                    href="lara-dark-teal.css" //theme
                />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
